#
# Module manifest for module 'Core.Powers'
#
# Generated by: example@example.com
#
# Generated on: 11/08/2016
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'Core.Powers.psm1'

# Modules to import as nested modules of the module specified in ModuleToProcess
# NestedModules = 'Core.about_Powers.ps1'

# List of all files packaged with this module
FileList = 'Core.Powers.psm1', 'Core.about_Powers.ps1', 'Core.Powers.psd1'

# Version number of this module.
ModuleVersion = '1.0'

# Author of this module
Author = 'example@example.com'

# Company or vendor of this module
CompanyName = 'COMPANY'

# Copyright statement for this module
Copyright = 'MIT License'

# Description of the functionality provided by this module
Description = 'Module Manager'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @('Core.about_Powers.ps1')

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()


# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

# ID used to uniquely identify this module
#GUID = 'e90170df-2694-481a-91c6-c7d98207c8c1'

}

